version: '2'
services:
 web:
  image: nginx
  ports:
   - 81:80
  volumes:
   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
   - ./src/public/:/var/www/html/src/public
  restart: always
  depends_on:
   - php-fpm
   - db

 php-fpm:
  build: ./docker
  volumes:
   - ./src/public/:/var/www/html/src/public

 db:
  image: postgres:13
  restart: always
  environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DB}
  ports:
   - 54324:5432
