services:
 web:
  image: nginx
  ports:
   - 81:80
  volumes:
   - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
   - ./:/var/www/html
  restart: always
  depends_on:
   - php-fpm
   - db

 php-fpm:
  build: ./docker
  volumes:
   - ./:/var/www/html

 db:
  image: postgres:13
  restart: always
  environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   - POSTGRES_DB=${POSTGRES_DB}
  ports:
   - 54322:5432
